# Generated by Django 3.1 on 2021-12-02 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AFSISIndicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.UUIDField()),
                ('user_id', models.CharField(max_length=30)),
                ('field_aluminium', models.FloatField(null=True)),
                ('field_bedrock', models.FloatField(null=True)),
                ('field_carbon', models.FloatField(null=True)),
                ('field_fcc', models.FloatField(null=True)),
                ('field_ph', models.FloatField(null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='afsisindicators',
            constraint=models.UniqueConstraint(fields=('field_id',), name='unique afsis row'),
        ),
    ]
