# Generated by Django 3.1 on 2020-08-30 17:07

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygonlayer',
            name='shpolygon',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, srid=4326),
        ),
    ]
