# Generated by Django 3.1 on 2020-09-09 09:39

from django.db import migrations

import uuid

def gen_uuid(apps, schema_editor):
    Model_ = apps.get_model('layers', 'polygonlayer')
    for row in Model_.objects.all():
        row.field_id = uuid.uuid4()
        row.save(update_fields=['field_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0003_auto_20200909_1238'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
