# Generated by Django 3.1 on 2020-09-09 09:39

from django.db import migrations, models

import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0004_auto_20200909_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polygonlayer',
            name='field_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
