# Generated by Django 3.1 on 2020-09-10 12:59

from django.contrib.postgres.operations import HStoreExtension
import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0005_auto_20200909_1239'),
    ]

    operations = [
        HStoreExtension(),
        migrations.AddField(
            model_name='pointlayer',
            name='field_attributes',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='polygonlayer',
            name='field_attributes',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict),
        ),
    ]
