# Generated by Django 3.1 on 2020-09-14 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0006_auto_20200910_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointlayer',
            name='user_id',
            field=models.CharField(default='5f34961f33d7d212dc71322c', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='polygonlayer',
            name='user_id',
            field=models.CharField(default='5f34961f33d7d212dc71322c', max_length=30),
            preserve_default=False,
        ),
    ]
