# Generated by Django 3.1 on 2020-10-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0011_auto_20201017_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldindicators',
            name='field_id',
            field=models.UUIDField(),
        ),
    ]
