# Generated by Django 3.1 on 2021-03-03 10:38

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields.hstore
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0013_arrayedfieldindicators'),
    ]

    operations = [
        migrations.CreateModel(
            name='GridLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('user_id', models.CharField(max_length=30)),
                ('count', models.FloatField(null=True)),
                ('field_attributes', django.contrib.postgres.fields.hstore.HStoreField(blank=True, default=dict)),
                ('shpolygon', django.contrib.gis.db.models.fields.PolygonField(blank=True, srid=4326, unique=True)),
            ],
        ),
    ]
