# Generated by Django 3.1 on 2021-03-10 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0015_auto_20210304_1251'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='arrayedfieldindicators',
            constraint=models.UniqueConstraint(fields=('field_id', 'indicator'), name='unique field indicators row'),
        ),
    ]
