# Generated by Django 3.1 on 2021-08-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0018_auto_20210803_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shuserdetail',
            name='center',
        ),
        migrations.AddField(
            model_name='shuserdetail',
            name='geometry',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='shuserdetail',
            name='type',
            field=models.CharField(default='Feature', max_length=15),
        ),
    ]
