# Generated by Django 3.1 on 2021-08-04 14:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0019_auto_20210803_1455'),
    ]

    operations = [
        migrations.CreateModel(
            name='GridJsonLayer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=15)),
                ('field_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('user_id', models.CharField(max_length=30)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('geometry', models.JSONField(blank=True, unique=True)),
            ],
        ),
    ]
