# Generated by Django 3.1 on 2021-08-05 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('layers', '0020_gridjsonlayer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GridLayer',
        ),
        migrations.DeleteModel(
            name='PolygonLayer',
        ),
    ]
