# Generated by Django 3.1 on 2021-12-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyFieldIndicators',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_id', models.UUIDField()),
                ('user_id', models.CharField(max_length=30)),
                ('date_observed', models.DateField()),
                ('field_ndvi', models.FloatField(blank=True, null=True)),
                ('field_ndwi', models.FloatField(blank=True, null=True)),
                ('field_precipitation', models.FloatField(blank=True, null=True)),
                ('field_temperature', models.FloatField(blank=True, null=True)),
                ('field_evapotranspiration', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.AddConstraint(
            model_name='weeklyfieldindicators',
            constraint=models.UniqueConstraint(fields=('field_id', 'date_observed'), name='unique weekly field indicators row'),
        ),
    ]
