# Generated by Django 3.1 on 2022-01-05 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indicator_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyfieldindicators',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
